apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
#  labels:
#    app: go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: h0si/cc-project-k8s
          ports:
            - containerPort: 1323
          env:
            - name: POSTGRES_WRITE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: WRITE_USERNAME
            - name: POSTGRES_WRITE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: WRITE_PASSWORD
            - name: POSTGRES_READ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: READ_USERNAME
            - name: POSTGRES_READ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: READ_PASSWORD
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: go-app-configmap
                  key: APP_PORT
          volumeMounts:
            - name: config-volume
              mountPath: /
              subPath: config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: go-app-configmap
