apiVersion: v1
kind: ConfigMap
metadata:
  name: go-app-configmap
data:
  config.yaml: |-
    DB:
      WRITE_HOST: db-headless-svc
      WRITE_PORT: "5432"
      READ_HOST: db-read-svc
      READ_PORT: "5432"
      DB_NAME: postgres
      SSL_MODE: prefer
    Check_Interval: "1"
  APP_PORT: "1323"